### PR TITLE
Automatic Differentiation Compatibility

### PR DESCRIPTION
**Pull request by jmurphy6895**
Added support for automatic differentiation capabilities with minor typing changes and a few convenience functions. 

Added tests to check for compatibility with ForwardDiff.jl via DifferentiationInterface.jl

### CODE REVIEW

**Comment by JRock95** [comment]
@ronisbr Here is the next update for the autodiff work. Don't run the tests yet, they will fail due to some issue in DifferentiationInterface.jl (See https://github.com/gdalle/DifferentiationInterface.jl/issues/525) But just to get some eyes on the new code in the meantime in case changes are needed.

**Comment by JRock95** [comment]
@ronisbr Ok, the issue was resolved, tests are passing and PR is ready for a full review whenever you have time

**Comment by ronisbr** [comment]
Hi @jmurphy6895 !

Thank you very much, I will take more time to analyze this because since it changes the return type of some functions, it might be breaking. If this modification breaks our current code on production, unfortunately we will need to postpone it a little bit until I have time to update everything.

**Comment by JRock95** [comment]
Sounds good, definitely understand. If it does break things, let me know if there's anything I can do to help

**Comment by ronisbr** [comment]
Hi @jmurphy6895 

Just one feedback (sorry for the delay). Unfortunately the return type change caused a lot of errors in our algorithms :( I did not investigate to check if those are easy fixes or not. One question: can we somehow add autodiff without this modification?

**Comment by JRock95** [comment]
Hey @ronisbr, let me run some experiments, I think might have an idea or two, probably won't be able to track them down until this weekend or next week though

**Comment by JRock95** [comment]
@ronisbr I reverted the return types and have a work-around with array comprehensions, it's a touch awkward and I do think that it makes sense for the geodetic_geocentric to be consistent with return types eventually -- some already return SVectors and other Tuples -- so it works for you I'm going to submit an issue to deal with it later, but its not blocking at the moment.

**Comment by ronisbr** [comment]
Hi @jmurphy6895 !

Excellent! The design we selected was to use `SVector` only if the return type is actually a vector. If you are returning a set of information (like latitude, longitude and altitude), then we used tuples.

**Comment by ronisbr** [comment]
Thanks @jmurphy6895 !

**Pull request merged**
